language: r
dist: trusty
sudo: false
cache: packages

r:
 - release
 - devel

r_github_packages:
  - r-hub/crancache

after_success:
  - test $TRAVIS_R_VERSION_STRING = 'release' && Rscript -e 'covr::codecov()'
